"""PostgreSQL store for extracted PDF catalogues.

The Catalogues page used to re-read a PDF on every open (5-20 s each). Each catalogue is
now extracted once, saved here, and read back in milliseconds. A new PDF is loaded only
when someone runs the load for it (``python -m src.cli catalogue-load``).

Tables, as laid out in the owner's diagram (2026-09-27):

* ``catalogues`` — one row per PDF: ``catalogue_id``, ``catalogue_no`` (the cover's
  publication number, unique, NULL where the book prints none), ``catalogue_year``,
  ``source_file`` (its path under ``pdf_catalogues``), with the file's SHA-256 so a
  changed file is noticed. Excluded catalogues are recorded with the reason, no parts.
* ``models`` — ``model_code`` (the variant, e.g. B65L) and ``model_name`` (its model
  folder, e.g. AEROX).
* ``catalogue_parts`` — one row per part row **per model it is fitted to**:
  ``section``, ``part_no``, ``description``, ``model_code`` (FK to ``models``),
  ``quantity`` for that model, ``remarks``. A row priced for no model is stored once
  with ``model_code`` NULL and a ``row_kind`` naming why (``kit_note``, ``kit_header``).
* ``catalogue_colours`` — the applicable-colour table as extracted.
* ``part_compatible_models`` (view) — per ``part_no``: its description and the
  ``compatible_models`` array ("AEROX - B65L"), plus a separator-free ``material_key``
  so an SAP material id finds it.

Everything the reader produced is kept, so a stored catalogue reads back as the same
``ExtractionResult`` a live extraction returns and the page cannot tell the two apart.
Every write is reconciled against the extraction it came from inside the transaction; a
mismatch rolls back.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import fields as dc_fields
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import psycopg
from loguru import logger
from psycopg.types.json import Jsonb

from src.catalogue.browser.agent import _has_qty, _variant_qty
from src.catalogue.browser.overrides import relative_key
from src.catalogue.browser.pdf_extractor import ExtractionResult
from src.core.errors import CatalogueStoreError
from src.core.settings import Settings, get_settings

#: Bumped whenever the reader changes what it extracts, so stored copies are refreshed.
EXTRACTOR_VERSION = "2026-09-26"

#: Databases whose schema this process has already ensured.
_SCHEMA_READY: set[str] = set()

DDL = """
CREATE TABLE IF NOT EXISTS catalogues (
    catalogue_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalogue_no        text UNIQUE,
    catalogue_year      smallint,
    source_file         text NOT NULL UNIQUE,
    -- reader detail, so a stored catalogue reads back exactly as extracted
    content_sha256      char(64) NOT NULL,
    model_no            text,
    variants            text[] NOT NULL DEFAULT '{}',
    status              text NOT NULL CHECK (status IN ('loaded', 'excluded')),
    excluded_reason     text,
    model_colour_source text,
    row_count           integer NOT NULL DEFAULT 0,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    extractor_version   text NOT NULL,
    loaded_at           timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS models (
    model_code  text PRIMARY KEY,
    model_name  text NOT NULL
);

CREATE TABLE IF NOT EXISTS catalogue_colours (
    catalogue_id    bigint NOT NULL REFERENCES catalogues ON DELETE CASCADE,
    sort_order      smallint NOT NULL,
    abbreviation    text NOT NULL,
    name            text,
    code            text,
    is_model_colour boolean NOT NULL DEFAULT false,
    source          text NOT NULL,
    PRIMARY KEY (catalogue_id, abbreviation)
);

CREATE TABLE IF NOT EXISTS catalogue_parts (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalogue_id  bigint NOT NULL REFERENCES catalogues ON DELETE CASCADE,
    section       text,
    part_no       text NOT NULL,
    description   text,
    model_code    text REFERENCES models (model_code),
    quantity      smallint,
    remarks       text,
    -- reader detail, so a stored catalogue reads back exactly as extracted
    row_no        integer NOT NULL,
    page          smallint,
    fig_no        text,
    ref_no        text,
    qty_raw       text,
    colour_hint   text,
    row_kind      text NOT NULL,
    qty_assumed   boolean NOT NULL DEFAULT false,
    extra         jsonb NOT NULL DEFAULT '{}'::jsonb
);
"""

#: Brings a database created by the first version of this module to the current shape:
#: bigint keys, catalogue_no, models, and model -> model_code as a foreign key. Every
#: step is idempotent, so it runs on each connection that ensures the schema.
MIGRATION = """
ALTER TABLE catalogues ADD COLUMN IF NOT EXISTS catalogue_no text;
DO $$
DECLARE t text;
BEGIN
    -- Widen the keys only while they are still integer: once the view exists, even a
    -- no-op ALTER TYPE on a column it reads is refused.
    FOREACH t IN ARRAY ARRAY['catalogues', 'catalogue_colours', 'catalogue_parts'] LOOP
        IF EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = t AND column_name = 'catalogue_id'
                   AND data_type = 'integer') THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN catalogue_id TYPE bigint', t);
        END IF;
    END LOOP;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'catalogues_catalogue_no_key') THEN
        ALTER TABLE catalogues ADD CONSTRAINT catalogues_catalogue_no_key UNIQUE (catalogue_no);
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'catalogue_parts' AND column_name = 'model') THEN
        ALTER TABLE catalogue_parts RENAME COLUMN model TO model_code;
    END IF;
END $$;
INSERT INTO models (model_code, model_name)
SELECT DISTINCT ON (p.model_code) p.model_code, split_part(c.source_file, '/', 1)
FROM catalogue_parts p JOIN catalogues c USING (catalogue_id)
WHERE p.model_code IS NOT NULL
ORDER BY p.model_code, c.source_file
ON CONFLICT (model_code) DO NOTHING;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'catalogue_parts_model_code_fkey') THEN
        ALTER TABLE catalogue_parts ADD CONSTRAINT catalogue_parts_model_code_fkey
            FOREIGN KEY (model_code) REFERENCES models (model_code);
    END IF;
END $$;
"""

#: Compatible model variants per part number. ``material_key`` is the part number with
#: every separator removed, so an SAP material id ("B65E390710") finds the catalogue's
#: "B65-E3907-10" — the same dash-insensitive identity the part master uses.
VIEWS = """
CREATE INDEX IF NOT EXISTS catalogue_parts_catalogue_row ON catalogue_parts (catalogue_id, row_no);
CREATE INDEX IF NOT EXISTS catalogue_parts_part_no ON catalogue_parts (part_no);
CREATE INDEX IF NOT EXISTS catalogue_parts_model_code ON catalogue_parts (model_code);
CREATE OR REPLACE VIEW part_compatible_models AS
SELECT
    p.part_no,
    mode() WITHIN GROUP (ORDER BY p.description) AS description,
    array_agg(DISTINCT m.model_name || ' - ' || m.model_code
              ORDER BY m.model_name || ' - ' || m.model_code) AS compatible_models,
    upper(regexp_replace(p.part_no, '[^A-Za-z0-9]', '', 'g')) AS material_key,
    count(DISTINCT p.catalogue_id) AS catalogue_count
FROM catalogue_parts p
JOIN models m USING (model_code)
JOIN catalogues c USING (catalogue_id)
WHERE c.status = 'loaded'
GROUP BY p.part_no;
"""


def material_key(part_no: str) -> str:
    """A part number or SAP material id with separators removed, upper-cased."""
    return re.sub(r"[^A-Za-z0-9]", "", part_no or "").upper()


def material_key_forms(key: str) -> list[str]:
    """The keys one part number is known by: its 10-digit and 12-digit forms.

    Business meaning: Yamaha writes the same part as "B65-E3907-10" in a catalogue and
    "B65-E3907-10-00" in the PN_Yamaha master — the 12-digit form appends "00". Matching
    exactly paired 6,961 of 15,815 catalogue numbers with the master; treating the two
    forms as one pairs 12,302.
    """
    forms = [key]
    if len(key) == 10:
        forms.append(key + "00")
    elif len(key) == 12 and key.endswith("00"):
        forms.append(key[:-2])
    return forms


#: Row keys with a column of their own; every other key rides in ``extra``.
_ROW_COLUMNS = frozenset(
    {
        "section",
        "fig_no",
        "ref_no",
        "part_no",
        "description",
        "qty",
        "remarks",
        "colour_hint",
        "page",
        "qty_assumed",
    }
)
#: ExtractionResult fields kept in ``catalogues.metadata`` rather than a column.
_META_FIELDS = (
    "pages_scanned",
    "sections_found",
    "ocr_flagged",
    "available_colours",
    "available_colour_map",
    "warnings",
    "column_layout",
    "column_display_labels",
    "model",
)


def file_sha256(path: Path) -> str:
    """SHA-256 of a source file, the identity a stored copy is checked against."""
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def connect(settings: Settings | None = None) -> psycopg.Connection:
    """Open a connection from the POSTGRES_* settings.

    Raises:
        CatalogueStoreError: the server is unreachable or refuses the credentials. The
            message never carries the password.
    """
    params = (settings or get_settings()).postgres_params()
    try:
        # Autocommit: each save is its own transaction (conn.transaction()), so a long
        # batch load commits catalogue by catalogue instead of all at the end.
        return psycopg.connect(**params, connect_timeout=5, autocommit=True)
    except psycopg.Error as exc:
        detail = str(exc).replace(params["password"], "***") if params["password"] else str(exc)
        raise CatalogueStoreError(
            f"cannot connect to {params['dbname']} at {params['host']}:{params['port']} "
            f"as {params['user']}: {detail.strip()}"
        ) from exc


def ensure_schema(conn: psycopg.Connection) -> None:
    """Create or upgrade the tables and the compatibility view. Idempotent.

    Runs once per process and database: the upgrade takes table locks, which a page
    request should not pay for on every call.
    """
    key = f"{conn.info.host}:{conn.info.port}/{conn.info.dbname}"
    if key in _SCHEMA_READY:
        return
    with conn.transaction():
        conn.execute(DDL)
        conn.execute(MIGRATION)
        conn.execute(VIEWS)
        conn.execute(PN_YAMAHA_DDL)
    _SCHEMA_READY.add(key)


def _row_kind(row: dict[str, Any]) -> str:
    if row.get("kit_note"):
        return "kit_note"
    if re.search(r"\bKIT\b|CONSISTING", (row.get("description") or "").upper()):
        return "kit_header"
    return "no_model"


def _quantity(text: str) -> int | None:
    m = re.search(r"\d+", text or "")
    return int(m.group()) if m else None


def _explode(result: ExtractionResult) -> list[dict[str, Any]]:
    """One record per part row per model it applies to; one NULL-model record otherwise.

    Business meaning: a quantity column is priced per model, so "1/1" over B65J and
    B65L is one of this part on each; a row priced for nobody is still kept.
    """
    variants = result.variants or ([result.model_no] if result.model_no else [])
    n = len(variants)
    out: list[dict[str, Any]] = []
    for row_no, row in enumerate(result.rows):
        qty_raw = row.get("qty") or ""
        base = {
            "row_no": row_no,
            "page": row.get("page"),
            "section": row.get("section"),
            "fig_no": row.get("fig_no"),
            "ref_no": row.get("ref_no"),
            "part_no": row.get("part_no") or "",
            "description": row.get("description"),
            "qty_raw": qty_raw,
            "remarks": row.get("remarks"),
            "colour_hint": row.get("colour_hint"),
            "qty_assumed": bool(row.get("qty_assumed")),
            "extra": {k: v for k, v in row.items() if k not in _ROW_COLUMNS},
        }
        live: list[tuple[str, int | None]] = []
        if n > 1:
            for i, variant in enumerate(variants):
                q = _variant_qty(qty_raw, i, n)
                if _has_qty(q):
                    live.append((variant, _quantity(q)))
        elif _has_qty(qty_raw):
            live.append((variants[0] if variants else None, _quantity(qty_raw)))
        if live:
            out += [{**base, "model_code": m, "quantity": q, "row_kind": "part"} for m, q in live]
        else:
            out.append({**base, "model_code": None, "quantity": None, "row_kind": _row_kind(row)})
    return out


def save_extraction(
    conn: psycopg.Connection, source_file: str, sha256: str, result: ExtractionResult
) -> int:
    """Replace one catalogue's stored copy with this extraction, reconciled on write.

    Returns:
        The catalogue_id.

    Raises:
        CatalogueStoreError: the extraction failed, or what landed in the database does
            not match it (rolled back).
    """
    if result.error:
        raise CatalogueStoreError(f"{source_file}: extraction failed: {result.error}")
    records = _explode(result)
    year = int(result.manufacture_year) if (result.manufacture_year or "").isdigit() else None
    metadata = {name: getattr(result, name) for name in _META_FIELDS}
    model_name = source_file.split("/")[0]
    with conn.transaction():
        catalogue_no = _free_catalogue_no(conn, result.catalogue_no, source_file, metadata)
        cur = conn.execute(
            """
            INSERT INTO catalogues (source_file, catalogue_no, content_sha256, catalogue_year,
                model_no, variants, status, excluded_reason, model_colour_source, row_count,
                metadata, extractor_version, loaded_at)
            VALUES (%s, %s, %s, %s, %s, %s, 'loaded', NULL, %s, %s, %s, %s, %s)
            ON CONFLICT (source_file) DO UPDATE SET
                catalogue_no = EXCLUDED.catalogue_no,
                content_sha256 = EXCLUDED.content_sha256,
                catalogue_year = EXCLUDED.catalogue_year,
                model_no = EXCLUDED.model_no,
                variants = EXCLUDED.variants,
                status = 'loaded',
                excluded_reason = NULL,
                model_colour_source = EXCLUDED.model_colour_source,
                row_count = EXCLUDED.row_count,
                metadata = EXCLUDED.metadata,
                extractor_version = EXCLUDED.extractor_version,
                loaded_at = EXCLUDED.loaded_at
            RETURNING catalogue_id
            """,
            (
                source_file,
                catalogue_no,
                sha256,
                year,
                result.model_no,
                list(result.variants or []),
                result.model_colour_source,
                len(result.rows),
                Jsonb(metadata),
                EXTRACTOR_VERSION,
                datetime.now(UTC),
            ),
        )
        catalogue_id = cur.fetchone()[0]
        conn.execute("DELETE FROM catalogue_colours WHERE catalogue_id = %s", (catalogue_id,))
        conn.execute("DELETE FROM catalogue_parts WHERE catalogue_id = %s", (catalogue_id,))
        with conn.cursor() as c:
            # Every model a part is fitted to exists in models first (model_code is a
            # foreign key). A code already recorded keeps the name it was first given.
            c.executemany(
                "INSERT INTO models (model_code, model_name) VALUES (%s, %s) "
                "ON CONFLICT (model_code) DO NOTHING",
                sorted({(r["model_code"], model_name) for r in records if r["model_code"]}),
            )
            c.executemany(
                """
                INSERT INTO catalogue_colours (catalogue_id, sort_order, abbreviation, name,
                    code, is_model_colour, source)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (catalogue_id, abbreviation) DO NOTHING
                """,
                [
                    (
                        catalogue_id,
                        i,
                        c_["abbreviation"],
                        c_.get("name"),
                        c_.get("code"),
                        bool(c_.get("is_model_colour")),
                        c_.get("source") or "table",
                    )
                    for i, c_ in enumerate(result.colour_codes or [])
                ],
            )
            c.executemany(
                """
                INSERT INTO catalogue_parts (catalogue_id, row_no, page, section, fig_no, ref_no,
                    part_no, description, model_code, quantity, qty_raw, remarks, colour_hint,
                    row_kind, qty_assumed, extra)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                [
                    (
                        catalogue_id,
                        r["row_no"],
                        r["page"],
                        r["section"],
                        r["fig_no"],
                        r["ref_no"],
                        r["part_no"],
                        r["description"],
                        r["model_code"],
                        r["quantity"],
                        r["qty_raw"],
                        r["remarks"],
                        r["colour_hint"],
                        r["row_kind"],
                        r["qty_assumed"],
                        Jsonb(r["extra"]),
                    )
                    for r in records
                ],
            )
        stored_rows, stored_records = conn.execute(
            "SELECT count(DISTINCT row_no), count(*) FROM catalogue_parts WHERE catalogue_id = %s",
            (catalogue_id,),
        ).fetchone()
        if stored_rows != len(result.rows) or stored_records != len(records):
            raise CatalogueStoreError(
                f"{source_file}: wrote {stored_rows} rows / {stored_records} records, "
                f"expected {len(result.rows)} / {len(records)}; rolled back"
            )
    logger.info(
        f"{source_file}: stored {len(result.rows)} rows as {len(records)} records "
        f"(catalogue_id {catalogue_id})"
    )
    return catalogue_id


def _free_catalogue_no(
    conn: psycopg.Connection, catalogue_no: str | None, source_file: str, metadata: dict[str, Any]
) -> str | None:
    """The catalogue number to store, or None if another catalogue already holds it.

    catalogue_no is unique. Two different files printing the same number is recorded as
    a warning on the second rather than failing its load.
    """
    if not catalogue_no:
        return None
    holder = conn.execute(
        "SELECT source_file FROM catalogues WHERE catalogue_no = %s AND source_file <> %s",
        (catalogue_no, source_file),
    ).fetchone()
    if holder is None:
        return catalogue_no
    metadata["warnings"] = [
        *(metadata.get("warnings") or []),
        f"catalogue_no {catalogue_no} is already held by {holder[0]}; not stored here",
    ]
    return None


def _backfill_catalogue_no(conn: psycopg.Connection, source_file: str, pdf_path: Path) -> None:
    """Give a current stored copy its catalogue number without re-extracting it.

    Copies stored before catalogue_no existed have it NULL; reading the cover is enough
    to fill it (a fraction of a second, against ~10 s for a full extraction).
    """
    from src.catalogue.browser.pdf_extractor import YamahaCatalogueExtractor

    row = conn.execute(
        "SELECT catalogue_no, metadata FROM catalogues WHERE source_file = %s", (source_file,)
    ).fetchone()
    if row is None or row[0] is not None or (row[1] or {}).get("catalogue_no_checked"):
        return
    metadata = dict(row[1] or {})
    found = YamahaCatalogueExtractor._extract_catalogue_no(pdf_path)
    with conn.transaction():
        number = _free_catalogue_no(conn, found, source_file, metadata)
        metadata["catalogue_no_checked"] = True
        conn.execute(
            "UPDATE catalogues SET catalogue_no = %s, metadata = %s WHERE source_file = %s",
            (number, Jsonb(metadata), source_file),
        )


def compatible_models(
    conn: psycopg.Connection, part_no: str | None = None, q: str | None = None, limit: int = 50
) -> list[dict[str, Any]]:
    """Compatible model variants for a part number or SAP material id.

    ``part_no`` matches exactly, ignoring separators ("B65E390710" finds
    "B65-E3907-10"); ``q`` matches any part number starting with it, or any description
    containing it.
    """
    if part_no:
        sql = "SELECT * FROM part_compatible_models WHERE material_key = %s"
        params: tuple[Any, ...] = (material_key(part_no),)
    elif q:
        sql = (
            "SELECT * FROM part_compatible_models WHERE material_key LIKE %s "
            "OR description ILIKE %s ORDER BY part_no LIMIT %s"
        )
        params = (material_key(q) + "%", f"%{q.strip()}%", limit)
    else:
        return []
    cur = conn.execute(sql, params)
    names = [d.name for d in cur.description]
    return [dict(zip(names, row, strict=True)) for row in cur.fetchall()]


def record_excluded(conn: psycopg.Connection, source_file: str, sha256: str, reason: str) -> None:
    """Record an excluded catalogue with its reason and no parts."""
    with conn.transaction():
        cur = conn.execute(
            """
            INSERT INTO catalogues (source_file, content_sha256, status, excluded_reason,
                extractor_version, loaded_at)
            VALUES (%s, %s, 'excluded', %s, %s, %s)
            ON CONFLICT (source_file) DO UPDATE SET
                content_sha256 = EXCLUDED.content_sha256, status = 'excluded',
                excluded_reason = EXCLUDED.excluded_reason, row_count = 0, catalogue_no = NULL,
                extractor_version = EXCLUDED.extractor_version, loaded_at = EXCLUDED.loaded_at
            RETURNING catalogue_id
            """,
            (source_file, sha256, reason, EXTRACTOR_VERSION, datetime.now(UTC)),
        )
        catalogue_id = cur.fetchone()[0]
        conn.execute("DELETE FROM catalogue_colours WHERE catalogue_id = %s", (catalogue_id,))
        conn.execute("DELETE FROM catalogue_parts WHERE catalogue_id = %s", (catalogue_id,))


def stored_state(conn: psycopg.Connection) -> dict[str, dict[str, Any]]:
    """Every stored catalogue's status, hash and reader version, keyed by source file."""
    rows = conn.execute(
        "SELECT source_file, status, content_sha256, extractor_version, row_count, "
        "excluded_reason, loaded_at FROM catalogues"
    ).fetchall()
    return {
        r[0]: {
            "status": r[1],
            "sha256": r[2],
            "extractor_version": r[3],
            "row_count": r[4],
            "excluded_reason": r[5],
            "loaded_at": r[6].isoformat() if r[6] else None,
        }
        for r in rows
    }


def load_extraction(
    conn: psycopg.Connection, source_file: str, pdf_path: Path
) -> ExtractionResult | None:
    """Rebuild the stored ExtractionResult for a catalogue, or None if it is not stored.

    Raises:
        CatalogueStoreError: the stored copy is incomplete (row count mismatch).
    """
    head = conn.execute(
        "SELECT catalogue_id, status, model_no, variants, catalogue_year, "
        "model_colour_source, row_count, metadata, catalogue_no "
        "FROM catalogues WHERE source_file = %s",
        (source_file,),
    ).fetchone()
    if head is None or head[1] != "loaded":
        return None
    catalogue_id, _, model_no, variants, year, colour_source, row_count, meta, cat_no = head
    colours = [
        {
            "abbreviation": r[0],
            "name": r[1],
            "code": r[2],
            "is_model_colour": r[3],
            **({"source": r[4]} if r[4] != "table" else {}),
        }
        for r in conn.execute(
            "SELECT abbreviation, name, code, is_model_colour, source FROM catalogue_colours "
            "WHERE catalogue_id = %s ORDER BY sort_order",
            (catalogue_id,),
        ).fetchall()
    ]
    rows: list[dict[str, Any]] = []
    last = -1
    for r in conn.execute(
        "SELECT DISTINCT ON (row_no) row_no, page, section, fig_no, ref_no, part_no, "
        "description, qty_raw, remarks, colour_hint, qty_assumed, extra "
        "FROM catalogue_parts WHERE catalogue_id = %s ORDER BY row_no, id",
        (catalogue_id,),
    ).fetchall():
        row_no, page, section, fig_no, ref_no, part_no, desc, qty_raw, rem, hint, assumed, extra = r
        if row_no == last:
            continue
        last = row_no
        row = {
            "section": section or "",
            "fig_no": fig_no or "",
            "ref_no": ref_no or "",
            "part_no": part_no,
            "description": desc or "",
            "qty": qty_raw or "",
            "remarks": rem or "",
            "nine_digit_part_no": "",
            "escort_part_no": "",
            "superseded_part_no": "",
            **(extra or {}),
        }
        if page is not None:
            row["page"] = page
        if hint:
            row["colour_hint"] = hint
        if assumed:
            row["qty_assumed"] = True
        rows.append(row)
    if len(rows) != row_count:
        raise CatalogueStoreError(
            f"{source_file}: stored copy has {len(rows)} rows, catalogue row says {row_count}"
        )
    known = {f.name for f in dc_fields(ExtractionResult)}
    return ExtractionResult(
        pdf_path=pdf_path,
        rows=rows,
        variants=list(variants or []),
        colour_codes=colours,
        model_colour_source=colour_source or "none",
        manufacture_year=str(year) if year else None,
        model_no=model_no,
        catalogue_no=cat_no,
        **{k: v for k, v in (meta or {}).items() if k in known},
    )


def source_key(pdf_path: Path) -> str:
    """The stored identity of a PDF: ``<model folder>/<file name>``."""
    return relative_key(pdf_path)


def dumps_state(state: dict[str, dict[str, Any]]) -> str:
    """Compact JSON of stored state, for the CLI."""
    return json.dumps(state, indent=1, default=str)


def read_catalogue(pdf_path: Path, max_pages: int = 500) -> tuple[ExtractionResult, str]:
    """The catalogue as the Catalogues page should show it, and where it came from.

    Returns the stored copy (``"database"``) when there is one and the PDF on disk still
    has the hash it was stored with. Otherwise the PDF is read live (``"pdf"``): a new
    catalogue not loaded yet, a file that changed since, or a database that cannot be
    reached. A live read is never written back — loading is a deliberate, manual step.
    """
    from src.catalogue.browser.pdf_extractor import YamahaCatalogueExtractor

    key = source_key(pdf_path)
    try:
        with connect() as conn:
            state = conn.execute(
                "SELECT content_sha256 FROM catalogues "
                "WHERE source_file = %s AND status = 'loaded'",
                (key,),
            ).fetchone()
            if state is not None and state[0] == file_sha256(pdf_path):
                stored = load_extraction(conn, key, pdf_path)
                if stored is not None:
                    return stored, "database"
            elif state is not None:
                logger.warning(f"{key}: PDF changed since it was stored; reading it live")
    except CatalogueStoreError as exc:
        logger.warning(f"catalogue store unavailable, reading {key} live: {exc}")
    return YamahaCatalogueExtractor(max_pages=max_pages).extract(pdf_path), "pdf"


class StoredCatalogueReader:
    """Drop-in for ``YamahaCatalogueExtractor.extract`` that prefers the stored copy.

    Handed to ``CatalogueAgent`` so the per-colour builds are resolved from the same
    stored extraction the parts table shows, instead of re-reading the PDF.
    """

    def __init__(self, max_pages: int = 500) -> None:
        self.max_pages = max_pages

    def extract(self, pdf_path: Path, model: str | None = None) -> ExtractionResult:
        result, _source = read_catalogue(pdf_path, self.max_pages)
        if model:
            result.model = model
        return result


def load_catalogues(
    pdfs: list[Path],
    *,
    force: bool = False,
    workers: int = 4,
    on_event: Any = None,
    settings: Settings | None = None,
) -> dict[str, Any]:
    """Extract PDFs and store them — the one batch load behind the CLI and the page button.

    A PDF whose stored copy has the same hash and reader version is skipped unless
    ``force``; excluded catalogues are recorded with their reason. PDFs are read in
    parallel and written one at a time, each in its own transaction, so a failure
    loses only that catalogue. ``on_event`` receives a dict per catalogue
    (``event``: loaded / skipped / excluded / failed) for progress reporting.

    Raises:
        CatalogueStoreError: the database cannot be reached.
    """
    from concurrent.futures import ThreadPoolExecutor

    from src.catalogue.browser.overrides import excluded
    from src.catalogue.browser.pdf_extractor import YamahaCatalogueExtractor

    settings = settings or get_settings()
    summary: dict[str, Any] = {
        "total": len(pdfs),
        "done": 0,
        "loaded": 0,
        "skipped": 0,
        "excluded": 0,
        "failed": [],
    }

    def emit(event: str, key: str, **extra: Any) -> None:
        summary["done"] += 1
        if on_event is not None:
            on_event({"event": event, "source_file": key, **extra, **summary})

    agent_cache = settings.marts_dir.parent / "catalogue_browser" / "agent_builds"
    with connect(settings) as conn:
        ensure_schema(conn)
        state = stored_state(conn)
        reasons = excluded()
        hashes = {pdf: file_sha256(pdf) for pdf in pdfs}
        # Byte-identical files are one catalogue, stored once under the first name in
        # sorted order (ALFA "Alpha B931_2XB1…" / "B931_2XB1…", NMAX "…050A" / "…050B").
        # catalogue_no is unique and both copies print the same one.
        copies: dict[str, set[str]] = {}
        for key, prior in state.items():
            if prior["status"] == "loaded":
                copies.setdefault(prior["sha256"], set()).add(key)
        for pdf, sha in hashes.items():
            if source_key(pdf) not in reasons:
                copies.setdefault(sha, set()).add(source_key(pdf))
        todo: list[tuple[Path, str, str]] = []
        for pdf in pdfs:
            key, sha = source_key(pdf), hashes[pdf]
            reason = reasons.get(key)
            if reason is None and min(copies.get(sha, {key})) != key:
                reason = f"byte-identical copy of {min(copies[sha])}; stored once"
            if reason:
                record_excluded(conn, key, sha, reason)
                summary["excluded"] += 1
                emit("excluded", key, reason=reason)
                continue
            prior = state.get(key)
            current = (
                prior is not None
                and prior["status"] == "loaded"
                and prior["sha256"] == sha
                and prior["extractor_version"] == EXTRACTOR_VERSION
            )
            if current and not force:
                _backfill_catalogue_no(conn, key, pdf)
                summary["skipped"] += 1
                emit("skipped", key)
                continue
            todo.append((pdf, key, sha))

        extractor = YamahaCatalogueExtractor(max_pages=500)
        with ThreadPoolExecutor(max_workers=max(1, workers)) as pool:
            jobs = pool.map(lambda job: (job, extractor.extract(job[0])), todo)
            for (_pdf, key, sha), result in jobs:
                try:
                    save_extraction(conn, key, sha, result)
                except CatalogueStoreError as exc:
                    summary["failed"].append({"source_file": key, "error": str(exc)})
                    emit("failed", key, error=str(exc))
                    continue
                summary["loaded"] += 1
                stale = agent_cache / (key.replace("/", "_").replace(" ", "_") + ".json")
                if stale.exists():
                    stale.unlink()  # its builds came from the previous extraction
                emit("loaded", key, rows=len(result.rows))
        if summary["loaded"] or summary["excluded"]:
            refresh_compatibility(conn)
    return summary


# ── PN_Yamaha master ──────────────────────────────────────────────────────────
# The distributor's own material master, Yamaha brand ("YM") only, loaded beside the
# catalogues so each material can be given the catalogue's part name and the model
# variants it is fitted to.

#: PN_Yamaha columns loaded, in order, and the table column each becomes.
PN_YAMAHA_COLUMNS: dict[str, str] = {
    "Material": "material",
    "Latest SS": "latest_ss",
    "Material description": "material_description",
    **{
        f"{n} Supersede": f"supersede_{i}"
        for i, n in enumerate(
            ("1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th"), start=1
        )
    },
}
PN_YAMAHA_BRAND = "YM"

PN_YAMAHA_DDL = """
CREATE TABLE IF NOT EXISTS pn_yamaha (
    material              text PRIMARY KEY,
    latest_ss             text,
    material_description  text,
    supersede_1  text, supersede_2  text, supersede_3  text, supersede_4  text,
    supersede_5  text, supersede_6  text, supersede_7  text, supersede_8  text,
    supersede_9  text, supersede_10 text,
    source_sha256         text,
    loaded_at             timestamptz NOT NULL
);

-- Stored rather than computed per read (a lookup took 1-2 s): refreshed by
-- refresh_compatibility() after every PN_Yamaha or catalogue load. A plain view of the
-- same name from an earlier version is replaced.
-- The definition carries a version in its comment; a stored copy built by an older
-- definition is dropped and rebuilt.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_views WHERE viewname = 'pn_yamaha_compatibility') THEN
        DROP VIEW pn_yamaha_compatibility;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_matviews WHERE matviewname = 'pn_yamaha_compatibility')
       AND coalesce(obj_description(to_regclass('pn_yamaha_compatibility'), 'pg_class'), '')
           <> 'chain-v3' THEN
        DROP MATERIALIZED VIEW pn_yamaha_compatibility;
    END IF;
END $$;
CREATE MATERIALIZED VIEW IF NOT EXISTS pn_yamaha_compatibility AS
WITH own AS (
    -- The material's own numbers: itself, its Latest SS, and the ten it superseded.
    -- ord keeps that order, so the material's own number wins.
    SELECT p.material, n.ord, n.field, n.number
    FROM pn_yamaha p
    CROSS JOIN LATERAL (VALUES
        (0, 'material', p.material), (1, 'latest_ss', p.latest_ss),
        (2, 'supersede_1', p.supersede_1), (3, 'supersede_2', p.supersede_2),
        (4, 'supersede_3', p.supersede_3), (5, 'supersede_4', p.supersede_4),
        (6, 'supersede_5', p.supersede_5), (7, 'supersede_6', p.supersede_6),
        (8, 'supersede_7', p.supersede_7), (9, 'supersede_8', p.supersede_8),
        (10, 'supersede_9', p.supersede_9), (11, 'supersede_10', p.supersede_10)
    ) AS n(ord, field, number)
), chain AS (
    SELECT material, coalesce(nullif(btrim(latest_ss), ''), material) AS chain_key
    FROM pn_yamaha
), members AS (
    -- The rest of the supersession chain: every material sharing this Latest SS, and
    -- the Latest SS material itself. Their rows can list old numbers this one does
    -- not: 1GC-E1636-19 lists none, its chain partner 1GC-E1636-19-00 lists
    -- 1GC-E1636-09-00, which is the catalogue's number.
    SELECT c1.material, c2.material AS member
    FROM chain c1 JOIN chain c2 ON c2.chain_key = c1.chain_key AND c2.material <> c1.material
    UNION
    SELECT c1.material, c1.chain_key
    FROM chain c1 JOIN pn_yamaha p ON p.material = c1.chain_key
    WHERE c1.chain_key <> c1.material
), numbers AS (
    SELECT material, ord, field, number FROM own
    UNION ALL
    -- Searched after the material's own twelve numbers (ord 20+).
    SELECT m.material, 20 + o.ord, 'chain', o.number
    FROM members m JOIN own o ON o.material = m.member
), keyed AS (
    -- Separators ignored; the 10- and 12-digit forms of one part are one part
    -- ("B65-E3907-10" in a catalogue is "B65-E3907-10-00" in PN_Yamaha).
    -- form_rank 0 is the number as written; 1 its other-length form. Where a catalogue
    -- lists both ("5YY-H2131-10" and "5YY-H2131-10-00") the exact one names the part.
    SELECT n.material, n.ord, n.field, k.key, k.form_rank
    FROM numbers n
    CROSS JOIN LATERAL (
        SELECT upper(regexp_replace(n.number, '[^A-Za-z0-9]', '', 'g')) AS base
    ) b
    CROSS JOIN LATERAL (VALUES
        (b.base, 0),
        (CASE WHEN length(b.base) = 10 THEN b.base || '00' END, 1),
        (CASE WHEN length(b.base) = 12 AND b.base LIKE '%00' THEN left(b.base, 10) END, 1)
    ) AS k(key, form_rank)
    WHERE k.key IS NOT NULL AND k.key <> ''
), matched_all AS (
    SELECT k.material, k.ord, k.form_rank, k.field, c.part_no, c.description,
           c.compatible_models, CASE WHEN k.ord < 20 THEN 0 ELSE 1 END AS tier
    FROM keyed k
    JOIN part_compatible_models c ON c.material_key = k.key
), matched AS (
    -- The chain (tier 1) is used only when the material's own twelve numbers (tier 0)
    -- find nothing — for the part name and for the compatible models alike.
    SELECT * FROM (
        SELECT m.*, min(tier) OVER (PARTITION BY material) AS best_tier FROM matched_all m
    ) t
    WHERE tier = best_tier
), per_material AS (
    SELECT material,
           (array_agg(description ORDER BY ord, form_rank, part_no))[1] AS catalogue_description,
           (array_agg(field ORDER BY ord, form_rank, part_no))[1] AS matched_on,
           array_agg(DISTINCT part_no ORDER BY part_no) AS catalogue_part_nos
    FROM matched
    GROUP BY material
), models AS (
    SELECT m.material, array_agg(DISTINCT x ORDER BY x) AS compatible_models
    FROM matched m CROSS JOIN LATERAL unnest(m.compatible_models) AS x
    GROUP BY m.material
)
SELECT p.material, p.latest_ss, p.material_description,
       pm.catalogue_description, mo.compatible_models,
       pm.matched_on, pm.catalogue_part_nos,
       (pm.material IS NOT NULL) AS in_catalogue,
       upper(regexp_replace(p.material, '[^A-Za-z0-9]', '', 'g')) AS material_key,
       upper(regexp_replace(coalesce(p.latest_ss, ''), '[^A-Za-z0-9]', '', 'g')) AS latest_ss_key
FROM pn_yamaha p
LEFT JOIN per_material pm USING (material)
LEFT JOIN models mo USING (material);
CREATE UNIQUE INDEX IF NOT EXISTS pn_yamaha_compatibility_material
    ON pn_yamaha_compatibility (material);
CREATE INDEX IF NOT EXISTS pn_yamaha_compatibility_material_key
    ON pn_yamaha_compatibility (material_key);
CREATE INDEX IF NOT EXISTS pn_yamaha_compatibility_latest_ss_key
    ON pn_yamaha_compatibility (latest_ss_key);
COMMENT ON MATERIALIZED VIEW pn_yamaha_compatibility IS 'chain-v3';
"""


def refresh_compatibility(conn: psycopg.Connection) -> None:
    """Recompute the stored PN_Yamaha compatibility after a load changed its inputs."""
    with conn.transaction():
        conn.execute("REFRESH MATERIALIZED VIEW pn_yamaha_compatibility")


def _missing(value: Any) -> bool:
    """None, NaN or a blank string."""
    if value is None:
        return True
    if isinstance(value, str):
        return not value.strip()
    return value != value  # NaN is the only value unequal to itself


def load_pn_yamaha(conn: psycopg.Connection) -> dict[str, Any]:
    """Replace the ``pn_yamaha`` table with PN_Yamaha's Yamaha-brand rows.

    Reads the converted PN_Yamaha workbook (``python -m src.cli ingest``), keeps Brand
    "YM", and loads Material, Latest SS, Material description and the ten Supersede
    columns in one transaction, reconciled by count before it commits. A row with no
    Material, or a Material repeated, is rejected and counted — never dropped silently.

    Business meaning: the material master every catalogue part is matched against.

    Raises:
        SourceDataError: the source is missing or lacks a declared column.
        CatalogueStoreError: the write did not reconcile (rolled back).
    """
    from src.core.errors import SourceDataError
    from src.io.excel import read_source, source_vintage

    frame = read_source("pn_yamaha")
    missing = [c for c in [*PN_YAMAHA_COLUMNS, "Brand"] if c not in frame.columns]
    if missing:
        raise SourceDataError(f"PN_Yamaha lacks column(s) {missing}")
    try:
        vintage = source_vintage("pn_yamaha")
        sha = str(vintage.get("sha256") or vintage.get("hash") or "")
    except SourceDataError:
        sha = ""
    brand = frame["Brand"].astype(str).str.strip().str.upper()
    ym = frame.loc[brand == PN_YAMAHA_BRAND, list(PN_YAMAHA_COLUMNS)]
    records = [
        [None if _missing(v) else str(v).strip() for v in values]
        for values in ym.itertuples(index=False, name=None)
    ]
    seen: set[str] = set()
    keep: list[list[Any]] = []
    rejected = {"blank material": 0, "duplicate material": 0}
    for record in records:
        if record[0] is None:
            rejected["blank material"] += 1
        elif record[0] in seen:
            rejected["duplicate material"] += 1
        else:
            seen.add(record[0])
            keep.append(record)
    now = datetime.now(UTC)
    columns = [*PN_YAMAHA_COLUMNS.values(), "source_sha256", "loaded_at"]
    with conn.transaction():
        conn.execute(PN_YAMAHA_DDL)
        conn.execute("TRUNCATE pn_yamaha")
        with (
            conn.cursor() as cur,
            cur.copy(f"COPY pn_yamaha ({', '.join(columns)}) FROM STDIN") as copy,
        ):
            for record in keep:
                copy.write_row([*record, sha, now])
        stored = conn.execute("SELECT count(*) FROM pn_yamaha").fetchone()[0]
        if stored != len(keep):
            raise CatalogueStoreError(
                f"pn_yamaha: wrote {stored} rows, expected {len(keep)}; rolled back"
            )
    refresh_compatibility(conn)
    summary = {
        "source_rows": len(frame),
        "brand": PN_YAMAHA_BRAND,
        "brand_rows": len(ym),
        "loaded": len(keep),
        "rejected": rejected,
        "source_sha256": sha,
    }
    logger.info(f"pn_yamaha: {summary}")
    return summary


def pn_yamaha_compatibility(
    conn: psycopg.Connection, material: str | None = None, q: str | None = None, limit: int = 50
) -> list[dict[str, Any]]:
    """PN_Yamaha materials with the catalogue part name and compatible model variants.

    ``material`` matches a Material or its Latest SS, separators ignored; ``q`` searches
    the material prefix or either description.
    """
    if material:
        # "B65E390710" finds the master's "B65-E3907-10-00": both digit forms are tried.
        forms = material_key_forms(material_key(material))
        sql = (
            "SELECT * FROM pn_yamaha_compatibility "
            "WHERE material_key = ANY(%s) OR latest_ss_key = ANY(%s) "
            "ORDER BY material LIMIT %s"
        )
        params: tuple[Any, ...] = (forms, forms, limit)
    elif q:
        sql = (
            "SELECT * FROM pn_yamaha_compatibility WHERE material ILIKE %s "
            "OR material_description ILIKE %s OR catalogue_description ILIKE %s "
            "ORDER BY material LIMIT %s"
        )
        text = q.strip()
        params = (text + "%", f"%{text}%", f"%{text}%", limit)
    else:
        return []
    cur = conn.execute(sql, params)
    names = [d.name for d in cur.description]
    return [dict(zip(names, row, strict=True)) for row in cur.fetchall()]
